<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
   //
    protected $table = "products";

    protected $fillable = ['id','name','descr','initialprice','end_date','image_url','slug','cat_id','buyer_id','successful_bid_id','created_at','updated_at'];



    /**
     * Display the specified resource.
     *
     * @param  int  
     * @return Response
     */
    public function category()
    {
    	return $this->belongsTo(Category::class,'cat_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class,'buyer_id');
    }

    public function bid()
    {
        return $this->hasOne('App\Bid', 'successful_bid_id');
    }

    public function bidProduct()
    {
        return $this->belongsTo('App\Bid');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($product) {

            $product->slug = str_slug($product->name);

            if (static::whereSlug($product->slug)->exists()) {
               $product->slug .= '-' . uniqid();
            }

        });
    }

}
